### ISSUE TITLE
manifold   meta-cell in Equ(4)

### ISSUE THREAD

**Issue by wuheng199112068** [CHENGY12/DMML#3]
Thank you for providing the code for your work. I have a question about the article, which manner do you construct the manifold based meta-cell? How to determine the alpha_{i}

**Comment by CHENGY12** [comment]
Thanks for your attention. In the current version, we use the center model (the alpha_{i}=1/N ) or the hard model (the alpha= {0,0,0,...,1,...,0} ) to determine the alpha_{i}. In the later versions, we have proposed to learn the alpha online.

**Comment by wuheng199112068** [comment]
Thank you for your quick reply. The value of alpha for the hard model is the alpha= {0,0,0,...,1,...,0}. I have a doubt that the support set (meta-cell) is not playing a manifold role?

**Comment by CHENGY12** [comment]
We calculated the point-to-manifold distance (from query to support set)by defining a hard mining distance, which selects the hardest sample in the support set to denote the manifold.
